MENU_MAIN = 'main'
MENU_SCHEDULE = 'schedule'
MENU_SCHEDULE_SHOW = 'schedule_show'
MENU_SCHEDULE_SHOW_ONE = 'schedule_one_day'
MENU_SEARCH_TEACHER = 'search_teacher'
MENU_TEACHER = 'teachers'
MENU_SCHEDULE_FOUND = 'teacher_schedule_show'
MENU_SETTINGS = 'settings'
MENU_SET_SETTINGS = 'set_settings'
MENU_CHANGE_GROUP = 'change_group'
MENU_SUBSCRIBE = 'subscribe_to_newsletter'
MENU_UNSUBSCRIBE = 'unsubscribe_to_newsletter'
MENU_UPDATE_SUBSCRIPTION = 'update_subscription'
MENU_CANCEL = 'cancel'
MENU_GET_CALENDAR = 'get_calendar'
MENU_CHOOSE_ROLE = 'choose_role'
MENU_SET_TEACHER = 'set_teacher'
MENU_SEARCH_SET_TEACHER = 'search_teacher_set'
MENU_SEARCH = 'search_menu'
MENU_SEARCH_GROUP = 'search_group'

ROLE_TEACHER = 'teacher'
ROLE_STUDENT = 'student'

SETTINGS_TYPE_GROUPS = 'toggle_groups'
SETTINGS_TYPE_LOCATION = 'toggle_location'

SUBSCRIPTION_TODAY = 'today'
SUBSCRIPTION_TOMORROW = 'tomorrow'
SUBSCRIPTION_TODAY_TOMORROW = 'today_and_tomorrow'
SUBSCRIPTION_WEEK = 'this_week'
SUBSCRIPTION_NEXT_WEEK = 'next_week'

CHANGES = 'CHANGES'
